import { Inter } from 'next/font/google'
import './globals.css'
import Footer from './components/navigation/footer'
import Menu from './components/navigation/menu'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Menu />
      
      {children}
      <Footer />
      </body>
    </html>
  )
}
